// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const CopyPlugin = require('copy-webpack-plugin');

// Utilities.
const path = require( 'path' );

// Add any a new entry point by extending the webpack config.
module.exports = {
	...defaultConfig,
	...{
		entry: {
			'js/editor':  path.resolve( process.cwd(), 'src/js',   'utk.js' ),
			'' : path.resolve( process.cwd(), 'src', 'style.scss') ,
			'css/editor': path.resolve( process.cwd(), 'src', 'editor-style.scss' ),
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin( {
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
			} ),
      new CopyPlugin({
        patterns: [
          { from: 'src/screenshot.png' },
          { from: 'src/readme.txt' },
          { from: 'src/theme.json' },
          { from: 'src/assets', to: 'assets' },
          { from: 'src/parts', to: 'parts' },
          { from: 'src/templates', to: 'templates' }, 
        ]
      })
		]
	}
};