name: Deploy to WP Engine Development
on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install Theme Dependencies
        run: npm ci

      - name: Build Theme
        run: npm run dist

      - name: Deploy Theme to WP Engine WDS
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: wds1dev
          SRC_PATH: 'dist/utkwds'
          REMOTE_PATH: 'wp-content/themes/'
          FLAGS: -r --delete

      - name: Deploy Theme to WP Engine Brand
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: brand4dev
          SRC_PATH: 'dist/utkwds'
          REMOTE_PATH: 'wp-content/themes/'
          FLAGS: -r --delete
